### ISSUE TITLE
Create Drive Loops

### ISSUE THREAD

**Issue by Pumuckl007** [FRCTeam2984/PowerUp2018#31]
Create The Loop that will allow the Drive System to do what it does.

**Comment by creikey** [comment]
Could you please go into more detail? I'm not sure how the Drive System is supposed 'to do what it does'

**Comment by Pumuckl007** [comment]
Currently there is a method registerEnabledLoops in Drive. However this method lacks an implementation. In this method A loop should be created, either as an inner class or explicit class, and registered. This loop should check the state of the drive subsystem. Depending on what state it should execute the methods that are necessary for the drive to operate.

For example, in PATH_FOLLOWING mode the loop should call updatePathFollower with the timestamp and optionally log to a CSVWriter.

**Comment by creikey** [comment]
@Pumuckl007 So what should the robot do in velocity_setpoint?

**Comment by creikey** [comment]
Wait nvmd

**Comment by creikey** [comment]
@Pumuckl007 the function `updateVelocitySetpoint(left_inches_per_sec, right_inches_per_sec);` needs a left and right inches per second. There isn't a function to do that in the class. Should I make those myself or make an issue?

**Comment by Pumuckl007** [comment]
All velocity inputs should already be in inches per second. If they are not it might be the wrong mode. Do you have a specific issue?

**Comment by creikey** [comment]
@Pumuckl007 Do you know where the api reference for CANTalon is? There's already left/right wheel master and slaves, so the speeds of the wheels should be in there, but I have no idea how to access those members.

**Comment by Pumuckl007** [comment]
You should not have to access the talons at all. But for future reference the docs can be found [here](http://www.ctr-electronics.com/downloads/api/java/html/index.html).

If you take a look at onLoop in your latest commit you have two cases VELOCITY_SETPOINT mode and PATH_FOLLOWING mode. In velocity setpoint mode the drive train should maintain a velocity that was set (this should be stored in an instance field). During pathfollowing mode the pathfollower issues commands.

Neither of these modes should need to do any converting. However, currently there is no OPEN_LOOP mode which would drive the talons in PERCENT_VBUS mode based on an input.

**Comment by creikey** [comment]
@Pumuckl007 So the `VELOCITY_SETPOINT` mode should constantly use `updateVelocitySetpoint` to update based on two variables that I make inside of the class that can be changed with another function, such as:

```java
private double leftSpeedInches;
private double rightSpeedInches;

void setLeftSpeed( double in_speed ) {
    this.leftSpeedInches = in_speed;
}

void setRightSpeed( double in_speed ) {
    this.rightSpeedInches = in_speed;
}

double getLeftSpeed() {
    return this.leftSpeedInches.clone();
}

double getRightSpeed() {
    return this.rightSpeedInches.clone();
}
````

**Comment by Pumuckl007** [comment]
Note quite. Another method, say setVelocitySetpoint, should set the velocity set point. Then VELOCITY_SETPOINT mode should call updateVelocitySetpoint repeatedly with this set point. You could use the motion object to keep track of this.
