### ISSUE TITLE
Create Open Loop drive Mode

### ISSUE THREAD

**Issue by Pumuckl007** [FRCTeam2984/PowerUp2018#32]
Currently the move method in Drive does not switch the drive mode from velocity control to PrecentVBUS (open loop). In addition, it would be helpful to reset the Nominal Output Voltage to zero.

**Comment by ruwix** [comment]
Why reset the nominal output voltage?

**Comment by Pumuckl007** [comment]
My thinking was to allow a continuous acceleration/deceleration of the robot. However, without comparing the two results on an actual robot it will be hard to decide. The situation I was thinking of is the one volt jump from +0.5 to -0.5.

**Comment by creikey** [comment]
@Pumuckl007 So you want to check if the `left` and `right` doubles are between 0.5 and -0.5, and if so, set `leftMaster` and `rightMaster` to zero?

```java
public void move(Motion motion) {
		double left = motion.getY() + motion.getRotation();
		double right = motion.getY() - motion.getRotation();
		double max = Math.max(abs(left), abs(right));
		if (max > 1 || max < -1) {
			left /= abs(max);
			right /= abs(max);
		}
		this.leftMaster.set(left);
		this.rightMaster.set(right);
}
```

**Comment by ruwix** [comment]
@creikey Yes

**Comment by creikey** [comment]
K this looks like a job for @Crimsonbaba

**Comment by ruwix** [comment]
@Crimsonbaba @creikey [https://ibb.co/cTn95R](https://ibb.co/cTn95R)

**Comment by Pumuckl007** [comment]
@creikey Remember that if you are setting the talon control mode to PrecentVBUS it will use the values 0-1 as a percentage of voltage outputted. Therefore an output of 0.5 Volts will correspond to a control value of about 0.04.

That being said there is a method in the CANTalon class that sets this threshold for you. I think it is setNominalOutputVoltage or something along those lines.
