### ISSUE TITLE
Variable starting location

### ISSUE THREAD

**Issue by Pumuckl007** [FRCTeam2984/PowerUp2018#66]
Add a system to allow the setting of the starting location in code. Then calculate the appropriate path to do the correct autonomous based on the starting location. With starting location I mean the distance from the end of the alliance wall.

**Comment by creikey** [comment]
So we should make six separate paths for each position?

**Comment by Pumuckl007** [comment]
There should only be four options at first as we are currently not focused on acquiring a cube in autonomous. There should be four separate paths/auto commands that take a distance as a parameter. This distance can be gotten via the smart dashboard or a switch on the robot.
