### ISSUE TITLE
Create LED Feedback

### ISSUE THREAD

**Issue by Pumuckl007** [FRCTeam2984/PowerUp2018#73]
Create a system to give feedback to the driver via an LED strip.

This will involve finding a controller for the LEDs. This controller will have to be able to handle the current wanted in addition to being compatible with the rules.

Then a subsystem has to be created where one can request the wanted state of the LEDs on the robot. (Feel free to choose a creative name).

**Comment by creikey** [comment]
Already finished and opened pull request. Not sure if it actually works though
